
package evg_belyavskii.fincurstask.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapService", targetNamespace = "http://ws.mkyong.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.mkyong.ws.Answer
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.mkyong.com/SoapService/getPriceStringRequest", output = "http://ws.mkyong.com/SoapService/getPriceStringResponse")
    public Answer getPriceString(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

}
